# Change these first
owner: ChesterHachirokuJamie # Your GitHub organization or username, where this repository lives
repo: stats # The name of this repository

sites:
  - name: Main Server (Server 02)
    check: "tcp-ping"
    url: chesterjamie.cn
    icon: https://chesterjamie.cn:8443/favicon.ico
    port: 5357
  - name: Chester Hachiroku Jamie Cloud Drive
    check: "tcp-ping"
    url: chesterjamie.cn
    icon: https://chesterjamie.cn:8443/favicon.ico
    port: 5000
  - name: Syncthing Endpoint
    check: "tcp-ping"
    url: chesterjamie.cn
    icon: https://chesterjamie.cn:8443/favicon.ico
    port: 8384
  - name: Tomcat Web Service
    check: "tcp-ping"
    url: chesterjamie.cn
    icon: https://chesterjamie.cn:8443/favicon.ico
    port: 8443
  - name: Matrix Synapse
    check: "tcp-ping"
    url: chesterjamie.cn
    icon: https://chesterjamie.cn:8443/favicon.ico
    port: 8448
  - name: Live Stream Server
    check: "tcp-ping"
    url: chesterjamie.cn
    icon: https://chesterjamie.cn:8443/favicon.ico
    port: 8888
  - name: Main Server Performance Panel
    check: "tcp-ping"
    url: chesterjamie.cn
    icon: https://chesterjamie.cn:8443/favicon.ico
    port: 11451
  - name: CHachirokuJamie上海电信中转服务器
    check: "tcp-ping"
    url: chesterjamie.cn
    icon: https://chesterjamie.cn:8443/favicon.ico
    port: 17014
  - name: CHachirokuJamie上海电信Guest中转服务器
    check: "tcp-ping"
    url: chesterjamie.cn
    icon: https://chesterjamie.cn:8443/favicon.ico
    port: 17015

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hachiroku.cn
  # baseUrl: /your-repo-name
  logoUrl: https://chesterjamie.cn:8443/favicon.ico
  favicon: https://chesterjamie.cn:8443/favicon.ico
  name: CHachirokuJamie Status
  introTitle: "**CHachirokuJamie Status Monitoring Panel**"
  introMessage: "***私有化部署，指光明航路***"
  navbar:
    - title: Status
      href: /
    - title: Performance
      href: http://chesterjamie.cn:11451
    - title: IFV-Lab
      href: https://status.ifvlab.com

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
